"""parsed_changes_table

Revision ID: 0004
Revises: 0003
Create Date: 2026-07-17 11:33:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0004"
down_revision: str | None = "0003"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "parsed_changes",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("pull_request_id", sa.Uuid(), nullable=False),
        sa.Column("functions_modified", postgresql.ARRAY(sa.VARCHAR()), nullable=False),
        sa.Column("classes_modified", postgresql.ARRAY(sa.VARCHAR()), nullable=False),
        sa.Column("routes", postgresql.ARRAY(sa.VARCHAR()), nullable=False),
        sa.Column("api_endpoints", postgresql.ARRAY(sa.VARCHAR()), nullable=False),
        sa.Column("sql_migrations", sa.Boolean(), nullable=False),
        sa.Column("dependencies", postgresql.ARRAY(sa.VARCHAR()), nullable=False),
        sa.Column("configuration", postgresql.ARRAY(sa.VARCHAR()), nullable=False),
        sa.Column("environment_variables", postgresql.ARRAY(sa.VARCHAR()), nullable=False),
        sa.Column("frontend_components", postgresql.ARRAY(sa.VARCHAR()), nullable=False),
        sa.Column("backend_services", postgresql.ARRAY(sa.VARCHAR()), nullable=False),
        sa.Column("tests", sa.Boolean(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["pull_request_id"], ["pull_requests.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_parsed_changes_id"), "parsed_changes", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_parsed_changes_pull_request_id"),
        "parsed_changes",
        ["pull_request_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_parsed_changes_pull_request_id"), table_name="parsed_changes"
    )
    op.drop_index(op.f("ix_parsed_changes_id"), table_name="parsed_changes")
    op.drop_table("parsed_changes")
    # ### end Alembic commands ###
