"""ai_analysis_table

Revision ID: 0005
Revises: 0004
Create Date: 2026-07-17 11:47:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0005"
down_revision: str | None = "0004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_analyses",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("pull_request_id", sa.Uuid(), nullable=False),
        sa.Column("summary", sa.TEXT(), nullable=False),
        sa.Column("engineering_impact", sa.TEXT(), nullable=False),
        sa.Column("business_impact", sa.TEXT(), nullable=False),
        sa.Column("affected_modules", postgresql.ARRAY(sa.VARCHAR()), nullable=False),
        sa.Column("security_impact", sa.TEXT(), nullable=False),
        sa.Column("database_changes", sa.TEXT(), nullable=False),
        sa.Column("api_changes", sa.TEXT(), nullable=False),
        sa.Column("configuration_changes", sa.TEXT(), nullable=False),
        sa.Column("risk_level", sa.VARCHAR(), nullable=False),
        sa.Column("deployment_notes", sa.TEXT(), nullable=False),
        sa.Column("testing_required", sa.TEXT(), nullable=False),
        sa.Column("breaking_changes", sa.Boolean(), nullable=False),
        sa.Column("release_notes", sa.TEXT(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["pull_request_id"], ["pull_requests.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_ai_analyses_id"), "ai_analyses", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_ai_analyses_pull_request_id"),
        "ai_analyses",
        ["pull_request_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_ai_analyses_pull_request_id"), table_name="ai_analyses"
    )
    op.drop_index(op.f("ix_ai_analyses_id"), table_name="ai_analyses")
    op.drop_table("ai_analyses")
    # ### end Alembic commands ###
