"""ai_advisor_table
# ruff: noqa: E501

Revision ID: 0006
Revises: 0005
Create Date: 2026-07-17 11:55:00.000000

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0006"
down_revision: str | None = "0005"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_advisors",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("pull_request_id", sa.Uuid(), nullable=False),
        sa.Column("missing_test_cases", postgresql.ARRAY(sa.VARCHAR()), nullable=False),
        sa.Column("potential_edge_cases", postgresql.ARRAY(sa.VARCHAR()), nullable=False),
        sa.Column(
            "suggested_documentation_updates", postgresql.ARRAY(sa.VARCHAR()), nullable=False
        ),
        sa.Column("possible_performance_issues", postgresql.ARRAY(sa.VARCHAR()), nullable=False),
        sa.Column("security_recommendations", postgresql.ARRAY(sa.VARCHAR()), nullable=False),
        sa.Column(
            "related_files_that_may_need_changes", postgresql.ARRAY(sa.VARCHAR()), nullable=False
        ),
        sa.Column("rollback_strategy", sa.TEXT(), nullable=False),
        sa.Column("deployment_checklist", postgresql.ARRAY(sa.VARCHAR()), nullable=False),
        sa.Column("future_refactoring_suggestions", postgresql.ARRAY(sa.VARCHAR()), nullable=False),
        sa.Column("suggested_reviewers", postgresql.ARRAY(sa.VARCHAR()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["pull_request_id"], ["pull_requests.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_ai_advisors_id"), "ai_advisors", ["id"], unique=False)
    op.create_index(
        op.f("ix_ai_advisors_pull_request_id"),
        "ai_advisors",
        ["pull_request_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_ai_advisors_pull_request_id"), table_name="ai_advisors")
    op.drop_index(op.f("ix_ai_advisors_id"), table_name="ai_advisors")
    op.drop_table("ai_advisors")
    # ### end Alembic commands ###
