"""pgvector_embeddings

Revision ID: 0007
Revises: 0006
Create Date: 2026-07-17 12:05:00.000000

"""

from collections.abc import Sequence

import pgvector.sqlalchemy
import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "0007"
down_revision: str | None = "0006"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("CREATE EXTENSION IF NOT EXISTS vector;")
    
    op.add_column(
        "ai_analyses",
        sa.Column(
            "summary_embedding",
            pgvector.sqlalchemy.Vector(dim=1536),
            nullable=True,
        ),
    )
    op.add_column(
        "ai_analyses",
        sa.Column(
            "engineering_impact_embedding",
            pgvector.sqlalchemy.Vector(dim=1536),
            nullable=True,
        ),
    )
    op.add_column(
        "ai_analyses",
        sa.Column(
            "release_notes_embedding",
            pgvector.sqlalchemy.Vector(dim=1536),
            nullable=True,
        ),
    )
    op.add_column(
        "ai_advisors",
        sa.Column(
            "advisor_embedding",
            pgvector.sqlalchemy.Vector(dim=1536),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ai_advisors", "advisor_embedding")
    op.drop_column("ai_analyses", "release_notes_embedding")
    op.drop_column("ai_analyses", "engineering_impact_embedding")
    op.drop_column("ai_analyses", "summary_embedding")
    
    op.execute("DROP EXTENSION IF EXISTS vector;")
    # ### end Alembic commands ###
