"""Add EngineeringDigest model

Revision ID: 7a8000098f09
Revises: 0007
Create Date: 2026-07-17 14:18:27.326407

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a8000098f09'
down_revision: str | Sequence[str] | None = '0007'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('engineering_digests',
    sa.Column('digest_type', sa.VARCHAR(length=50), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('markdown_content', sa.TEXT(), nullable=False),
    sa.Column('structured_data', sa.dialects.postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=False),
    sa.Column('id', sa.Uuid(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_engineering_digests_digest_type'), 'engineering_digests', ['digest_type'], unique=False)
    op.drop_index(op.f('ix_ai_advisors_id'), table_name='ai_advisors')
    op.drop_index(op.f('ix_ai_analyses_id'), table_name='ai_analyses')
    op.drop_constraint(op.f('uq_commits_pr_sha'), 'commits', type_='unique')
    op.drop_constraint(op.f('uq_github_installation_id'), 'github_installations', type_='unique')
    op.drop_constraint(op.f('uq_github_repo_id'), 'github_repositories', type_='unique')
    op.drop_index(op.f('ix_parsed_changes_id'), table_name='parsed_changes')
    op.drop_constraint(op.f('uq_pull_requests_github_pr_id'), 'pull_requests', type_='unique')
    op.drop_constraint(op.f('uq_raw_event_delivery_id'), 'raw_events', type_='unique')
    op.drop_constraint(op.f('uq_reviewers_github_review_id'), 'reviewers', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('uq_reviewers_github_review_id'), 'reviewers', ['github_review_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_raw_event_delivery_id'), 'raw_events', ['delivery_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_pull_requests_github_pr_id'), 'pull_requests', ['github_pr_id'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_parsed_changes_id'), 'parsed_changes', ['id'], unique=False)
    op.create_unique_constraint(op.f('uq_github_repo_id'), 'github_repositories', ['github_repo_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_github_installation_id'), 'github_installations', ['github_installation_id'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('uq_commits_pr_sha'), 'commits', ['pull_request_id', 'github_commit_sha'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_ai_analyses_id'), 'ai_analyses', ['id'], unique=False)
    op.create_index(op.f('ix_ai_advisors_id'), 'ai_advisors', ['id'], unique=False)
    op.drop_index(op.f('ix_engineering_digests_digest_type'), table_name='engineering_digests')
    op.drop_table('engineering_digests')
    # ### end Alembic commands ###
